baseURL = "https://mrcarri.github.io/mrcarri.dev/"
languageCode = "en-us"
title = "MrCarri Dev Blog"
theme = "papermod"      # O el tema que estés usando
paginate = 5            # Posts por página
enableGitInfo = true    # Útil para mostrar fecha de última actualización