baseURL = "https://mrcarri.dev/"
languageCode = "en-us"
title = "MrCarri Dev Blog"
theme = "papermod"
relativeURLs = false
canonifyURLs = true

[params]
mainSections = ["posts"]
[params.homeInfoParams]
Title = "Hi there, I'm Carri."
Content = "I'm a Software Engineer based in Barcelona, specializing in backend development and the implementation of AI solutions. This blog serves as my personal code laboratory where I document my self-hosted inventions, infrastructure projects, and technical experiments built during my spare time."
[[params.socialIcons]]
name = "github"
url = "https://github.com/MrCarri"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/alexandre-carrillo-costa"

# [[params.socialIcons]]
# name = "BuyMeACoffee"
# url = "https://www.buymeacoffee.com/mrcarri"
# # El título es opcional, pero mejora el accesibilidad al pasar el ratón.
# title = "Support my projects"

# URL opcional a tu página de Política de Privacidad (Muy recomendado para GDPR)
# privacy_page = "/privacy-policy/"

#[params.analytics]
# Reemplaza 'G-XXXXXXXXXX' con tu ID real de Google Analytics 4 (GA4)
#google = "G-XXXXXXXXXX"

[params.footer]
hideCopyright = true
text = "© 2025 MrCarri Dev Blog"

[menu]
[[menu.main]]
identifier = "about"
name = "About Me"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "articles"
name = "Articles"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/MrCarri"
weight = 30
# Opcional: Para abrir el enlace en una nueva pestaña
[menu.main.params]
target = "_blank"
[[menu.main]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://linkedin.com/in/alexandre-carrillo-costa"
weight = 40
# Opcional: Para abrir el enlace en una nueva pestaña
[menu.main.params]
target = "_blank"
