baseURL = "https://mrcarri.dev/"
languageCode = "en-us"
title = "MrCarri's Code Lab"
theme = "PaperMod"

[params]

  [params.homeInfoParams]
    Title = "Hi there, I'm MrCarri."
    Content = "Documenting personal back-end solutions, AI prompt engineering, and my self-hosted inventions."